version: 2.1

orbs:
  ruby: circleci/ruby@1.1.0

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.1-node
        environment:
          BUNDLER_VERSION: 2.2.7
    steps:
      - checkout
      - run: gem install bundler -v 2.2.7
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/install-deps

  test:
    parallelism: 3
    docker:
      - image: circleci/ruby:2.7.1-node-browsers
        environment:
          DB_HOST: 127.0.0.1
          RAILS_ENV: test
          BUNDLER_VERSION: 2.2.7
      - image: circleci/mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: "true"
          MYSQL_ROOT_HOST: "%"

    steps:
      - checkout
      - ruby/install-deps
      - run: yarn install
      - run: mv config/database.yml.ci config/database.yml
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:3306 -timeout 1m
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load
      - run: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3
      - run: mkdir ~/rspec
      - run:
          command: bundle exec rspec --format progress --format RspecJunitFormatter -o ~/rspec/rspec.xml
          when: always
      - store_test_results:
          path: ~/rspec
          
  deploy:
    docker:
      - image: circleci/ruby:2.7.1-node
        environment:
          BUNDLER_VERSION: 2.2.7
    steps:
      - checkout
      - ruby/install-deps
      - add_ssh_keys:
          fingerprints: "eb:59:0f:8e:3e:ec:9b:38:f8:df:1c:be:8a:bc:a4:f8"
      - deploy:
          name: Capistrano deploy
          command: bundle exec cap production deploy

workflows:
  version: 2.1
  build_accept_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master