Card.create(name: '聖霊王アルファディオス(仮)', race: '光')
Card.create(name: 'ロスト・ソウル(仮)', race: '闇')
Pack.create(pack_name: 'DMPP-01:超獣の始動(仮)')
Pack.create(pack_name: 'DMPP-02:伝説の再誕(仮)')
PackRarityRate.create(rarity: 'SR', rarity_weight: '3', pack_id: '1')
PackRarityRate.create(rarity: 'VR', rarity_weight: '9', pack_id: '1')
PackRarityRate.create(rarity: 'R', rarity_weight: '24', pack_id: '1')
PackRarityRate.create(rarity: 'UC', rarity_weight: '60', pack_id: '1')
PackRarityRate.create(rarity: 'C', rarity_weight: '104', pack_id: '1')
PackRarityRate.create(rarity: 'SR', rarity_weight: '3', pack_id: '2')
PackRarityRate.create(rarity: 'VR', rarity_weight: '9', pack_id: '2')
PackRarityRate.create(rarity: 'R', rarity_weight: '24', pack_id: '2')
PackRarityRate.create(rarity: 'UC', rarity_weight: '60', pack_id: '2')
PackRarityRate.create(rarity: 'C', rarity_weight: '104', pack_id: '2')
