Card.create(name: 'SR1-1')
Card.create(name: 'SR1-2')
Card.create(name: 'SR1-3')
Card.create(name: 'SR1-4')
Card.create(name: 'SR1-5')
Card.create(name: 'SR1-6')
Card.create(name: 'SR1-7')
Card.create(name: 'SR1-8')
Card.create(name: 'SR1-9')
Card.create(name: 'SR1-10')
Card.create(name: 'VR1-1')
Card.create(name: 'VR1-2')
Card.create(name: 'VR1-3')
Card.create(name: 'VR1-4')
Card.create(name: 'VR1-5')
Card.create(name: 'VR1-6')
Card.create(name: 'VR1-7')
Card.create(name: 'VR1-8')
Card.create(name: 'VR1-9')
Card.create(name: 'VR1-10')
Card.create(name: 'R1-1')
Card.create(name: 'R1-2')
Card.create(name: 'R1-3')
Card.create(name: 'R1-4')
Card.create(name: 'R1-5')
Card.create(name: 'R1-6')
Card.create(name: 'R1-7')
Card.create(name: 'R1-8')
Card.create(name: 'R1-9')
Card.create(name: 'R1-10')
Card.create(name: 'R1-11')
Card.create(name: 'R1-12')
Card.create(name: 'R1-13')
Card.create(name: 'R1-14')
Card.create(name: 'R1-15')
Card.create(name: 'R1-16')
Card.create(name: 'R1-17')
Card.create(name: 'R1-18')
Card.create(name: 'R1-19')
Card.create(name: 'R1-20')
Card.create(name: 'UC1-1')
Card.create(name: 'UC1-2')
Card.create(name: 'UC1-3')
Card.create(name: 'UC1-4')
Card.create(name: 'UC1-5')
Card.create(name: 'UC1-6')
Card.create(name: 'UC1-7')
Card.create(name: 'UC1-8')
Card.create(name: 'UC1-9')
Card.create(name: 'UC1-10')
Card.create(name: 'UC1-11')
Card.create(name: 'UC1-12')
Card.create(name: 'UC1-13')
Card.create(name: 'UC1-14')
Card.create(name: 'UC1-15')
Card.create(name: 'UC1-16')
Card.create(name: 'UC1-17')
Card.create(name: 'UC1-18')
Card.create(name: 'UC1-19')
Card.create(name: 'UC1-20')
Card.create(name: 'C1-1')
Card.create(name: 'C1-2')
Card.create(name: 'C1-3')
Card.create(name: 'C1-4')
Card.create(name: 'C1-5')
Card.create(name: 'C1-6')
Card.create(name: 'C1-7')
Card.create(name: 'C1-8')
Card.create(name: 'C1-9')
Card.create(name: 'C1-10')
Card.create(name: 'C1-11')
Card.create(name: 'C1-12')
Card.create(name: 'C1-13')
Card.create(name: 'C1-14')
Card.create(name: 'C1-15')
Card.create(name: 'C1-16')
Card.create(name: 'C1-17')
Card.create(name: 'C1-18')
Card.create(name: 'C1-19')
Card.create(name: 'C1-20')
Card.create(name: 'C1-21')
Card.create(name: 'C1-22')
Card.create(name: 'C1-23')
Card.create(name: 'C1-24')
Card.create(name: 'C1-25')

Card.create(name: 'SR2-1')
Card.create(name: 'SR2-2')
Card.create(name: 'SR2-3')
Card.create(name: 'SR2-4')
Card.create(name: 'SR2-5')
Card.create(name: 'SR2-6')
Card.create(name: 'SR2-7')
Card.create(name: 'SR2-8')
Card.create(name: 'SR2-9')
Card.create(name: 'SR2-10')
Card.create(name: 'VR2-1')
Card.create(name: 'VR2-2')
Card.create(name: 'VR2-3')
Card.create(name: 'VR2-4')
Card.create(name: 'VR2-5')
Card.create(name: 'VR2-6')
Card.create(name: 'VR2-7')
Card.create(name: 'VR2-8')
Card.create(name: 'VR2-9')
Card.create(name: 'VR2-10')
Card.create(name: 'R2-1')
Card.create(name: 'R2-2')
Card.create(name: 'R2-3')
Card.create(name: 'R2-4')
Card.create(name: 'R2-5')
Card.create(name: 'R2-6')
Card.create(name: 'R2-7')
Card.create(name: 'R2-8')
Card.create(name: 'R2-9')
Card.create(name: 'R2-10')
Card.create(name: 'R2-11')
Card.create(name: 'R2-12')
Card.create(name: 'R2-13')
Card.create(name: 'R2-14')
Card.create(name: 'R2-15')
Card.create(name: 'R2-16')
Card.create(name: 'R2-17')
Card.create(name: 'R2-18')
Card.create(name: 'R2-19')
Card.create(name: 'R2-20')
Card.create(name: 'UC2-1')
Card.create(name: 'UC2-2')
Card.create(name: 'UC2-3')
Card.create(name: 'UC2-4')
Card.create(name: 'UC2-5')
Card.create(name: 'UC2-6')
Card.create(name: 'UC2-7')
Card.create(name: 'UC2-8')
Card.create(name: 'UC2-9')
Card.create(name: 'UC2-10')
Card.create(name: 'UC2-11')
Card.create(name: 'UC2-12')
Card.create(name: 'UC2-13')
Card.create(name: 'UC2-14')
Card.create(name: 'UC2-15')
Card.create(name: 'UC2-16')
Card.create(name: 'UC2-17')
Card.create(name: 'UC2-18')
Card.create(name: 'UC2-19')
Card.create(name: 'UC2-20')
Card.create(name: 'C2-1')
Card.create(name: 'C2-2')
Card.create(name: 'C2-3')
Card.create(name: 'C2-4')
Card.create(name: 'C2-5')
Card.create(name: 'C2-6')
Card.create(name: 'C2-7')
Card.create(name: 'C2-8')
Card.create(name: 'C2-9')
Card.create(name: 'C2-10')
Card.create(name: 'C2-11')
Card.create(name: 'C2-12')
Card.create(name: 'C2-13')
Card.create(name: 'C2-14')
Card.create(name: 'C2-15')
Card.create(name: 'C2-16')
Card.create(name: 'C2-17')
Card.create(name: 'C2-18')
Card.create(name: 'C2-19')
Card.create(name: 'C2-20')
Card.create(name: 'C2-21')
Card.create(name: 'C2-22')
Card.create(name: 'C2-23')
Card.create(name: 'C2-24')
Card.create(name: 'C2-25')

Pack.create(pack_name: 'DMPP-01:超獣の始動(単発)', pack_num: '1')
Pack.create(pack_name: 'DMPP-01:超獣の始動(10連)', pack_num: '10')
Pack.create(pack_name: 'DMPP-02:伝説の再誕(単発)', pack_num: '1')
Pack.create(pack_name: 'DMPP-02:伝説の再誕(10連)', pack_num: '10')

PackRarityRate.create(rarity: 'SR', weight: '3', pack_id: '1')
PackRarityRate.create(rarity: 'VR', weight: '9', pack_id: '1')
PackRarityRate.create(rarity: 'R', weight: '24', pack_id: '1')
PackRarityRate.create(rarity: 'UC', weight: '60', pack_id: '1')
PackRarityRate.create(rarity: 'C', weight: '104', pack_id: '1')
PackRarityRate.create(rarity: 'SR', weight: '3', pack_id: '2')
PackRarityRate.create(rarity: 'VR', weight: '9', pack_id: '2')
PackRarityRate.create(rarity: 'R', weight: '24', pack_id: '2')
PackRarityRate.create(rarity: 'UC', weight: '60', pack_id: '2')
PackRarityRate.create(rarity: 'C', weight: '104', pack_id: '2')
PackRarityRate.create(rarity: 'SR', weight: '3', pack_id: '3')
PackRarityRate.create(rarity: 'VR', weight: '9', pack_id: '3')
PackRarityRate.create(rarity: 'R', weight: '24', pack_id: '3')
PackRarityRate.create(rarity: 'UC', weight: '60', pack_id: '3')
PackRarityRate.create(rarity: 'C', weight: '104', pack_id: '3')
PackRarityRate.create(rarity: 'SR', weight: '3', pack_id: '4')
PackRarityRate.create(rarity: 'VR', weight: '9', pack_id: '4')
PackRarityRate.create(rarity: 'R', weight: '24', pack_id: '4')
PackRarityRate.create(rarity: 'UC', weight: '60', pack_id: '4')
PackRarityRate.create(rarity: 'C', weight: '104', pack_id: '4')

PackCardRate.create(card_name: 'SR1-1', card_number: '1', weight: '1', pack_rarity_rate_id: '1')
PackCardRate.create(card_name: 'SR1-2', card_number: '2', weight: '1', pack_rarity_rate_id: '1')
PackCardRate.create(card_name: 'SR1-3', card_number: '3', weight: '1', pack_rarity_rate_id: '1')
PackCardRate.create(card_name: 'SR1-4', card_number: '4', weight: '1', pack_rarity_rate_id: '1')
PackCardRate.create(card_name: 'SR1-5', card_number: '5', weight: '1', pack_rarity_rate_id: '1')
PackCardRate.create(card_name: 'SR1-6', card_number: '6', weight: '1', pack_rarity_rate_id: '1')
PackCardRate.create(card_name: 'SR1-7', card_number: '7', weight: '1', pack_rarity_rate_id: '1')
PackCardRate.create(card_name: 'SR1-8', card_number: '8', weight: '1', pack_rarity_rate_id: '1')
PackCardRate.create(card_name: 'SR1-9', card_number: '9', weight: '1', pack_rarity_rate_id: '1')
PackCardRate.create(card_name: 'SR1-10', card_number: '10', weight: '1', pack_rarity_rate_id: '1')
PackCardRate.create(card_name: 'VR1-1', card_number: '11', weight: '1', pack_rarity_rate_id: '2')
PackCardRate.create(card_name: 'VR1-2', card_number: '12', weight: '1', pack_rarity_rate_id: '2')
PackCardRate.create(card_name: 'VR1-3', card_number: '13', weight: '1', pack_rarity_rate_id: '2')
PackCardRate.create(card_name: 'VR1-4', card_number: '14', weight: '1', pack_rarity_rate_id: '2')
PackCardRate.create(card_name: 'VR1-5', card_number: '15', weight: '1', pack_rarity_rate_id: '2')
PackCardRate.create(card_name: 'VR1-6', card_number: '16', weight: '1', pack_rarity_rate_id: '2')
PackCardRate.create(card_name: 'VR1-7', card_number: '17', weight: '1', pack_rarity_rate_id: '2')
PackCardRate.create(card_name: 'VR1-8', card_number: '18', weight: '1', pack_rarity_rate_id: '2')
PackCardRate.create(card_name: 'VR1-9', card_number: '19', weight: '1', pack_rarity_rate_id: '2')
PackCardRate.create(card_name: 'VR1-10', card_number: '20', weight: '1', pack_rarity_rate_id: '2')
PackCardRate.create(card_name: 'R1-1', card_number: '21', weight: '1', pack_rarity_rate_id: '3')
PackCardRate.create(card_name: 'R1-2', card_number: '22', weight: '1', pack_rarity_rate_id: '3')
PackCardRate.create(card_name: 'R1-3', card_number: '23', weight: '1', pack_rarity_rate_id: '3')
PackCardRate.create(card_name: 'R1-4', card_number: '24', weight: '1', pack_rarity_rate_id: '3')
PackCardRate.create(card_name: 'R1-5', card_number: '25', weight: '1', pack_rarity_rate_id: '3')
PackCardRate.create(card_name: 'R1-6', card_number: '26', weight: '1', pack_rarity_rate_id: '3')
PackCardRate.create(card_name: 'R1-7', card_number: '27', weight: '1', pack_rarity_rate_id: '3')
PackCardRate.create(card_name: 'R1-8', card_number: '28', weight: '1', pack_rarity_rate_id: '3')
PackCardRate.create(card_name: 'R1-9', card_number: '29', weight: '1', pack_rarity_rate_id: '3')
PackCardRate.create(card_name: 'R1-10', card_number: '30', weight: '1', pack_rarity_rate_id: '3')
PackCardRate.create(card_name: 'R1-11', card_number: '31', weight: '1', pack_rarity_rate_id: '3')
PackCardRate.create(card_name: 'R1-12', card_number: '32', weight: '1', pack_rarity_rate_id: '3')
PackCardRate.create(card_name: 'R1-13', card_number: '33', weight: '1', pack_rarity_rate_id: '3')
PackCardRate.create(card_name: 'R1-14', card_number: '34', weight: '1', pack_rarity_rate_id: '3')
PackCardRate.create(card_name: 'R1-15', card_number: '35', weight: '1', pack_rarity_rate_id: '3')
PackCardRate.create(card_name: 'R1-16', card_number: '36', weight: '1', pack_rarity_rate_id: '3')
PackCardRate.create(card_name: 'R1-17', card_number: '37', weight: '1', pack_rarity_rate_id: '3')
PackCardRate.create(card_name: 'R1-18', card_number: '38', weight: '1', pack_rarity_rate_id: '3')
PackCardRate.create(card_name: 'R1-19', card_number: '39', weight: '1', pack_rarity_rate_id: '3')
PackCardRate.create(card_name: 'R1-20', card_number: '40', weight: '1', pack_rarity_rate_id: '3')
PackCardRate.create(card_name: 'UC1-1', card_number: '41', weight: '1', pack_rarity_rate_id: '4')
PackCardRate.create(card_name: 'UC1-2', card_number: '42', weight: '1', pack_rarity_rate_id: '4')
PackCardRate.create(card_name: 'UC1-3', card_number: '43', weight: '1', pack_rarity_rate_id: '4')
PackCardRate.create(card_name: 'UC1-4', card_number: '44', weight: '1', pack_rarity_rate_id: '4')
PackCardRate.create(card_name: 'UC1-5', card_number: '45', weight: '1', pack_rarity_rate_id: '4')
PackCardRate.create(card_name: 'UC1-6', card_number: '46', weight: '1', pack_rarity_rate_id: '4')
PackCardRate.create(card_name: 'UC1-7', card_number: '47', weight: '1', pack_rarity_rate_id: '4')
PackCardRate.create(card_name: 'UC1-8', card_number: '48', weight: '1', pack_rarity_rate_id: '4')
PackCardRate.create(card_name: 'UC1-9', card_number: '49', weight: '1', pack_rarity_rate_id: '4')
PackCardRate.create(card_name: 'UC1-10', card_number: '50', weight: '1', pack_rarity_rate_id: '4')
PackCardRate.create(card_name: 'UC1-11', card_number: '51', weight: '1', pack_rarity_rate_id: '4')
PackCardRate.create(card_name: 'UC1-12', card_number: '52', weight: '1', pack_rarity_rate_id: '4')
PackCardRate.create(card_name: 'UC1-13', card_number: '53', weight: '1', pack_rarity_rate_id: '4')
PackCardRate.create(card_name: 'UC1-14', card_number: '54', weight: '1', pack_rarity_rate_id: '4')
PackCardRate.create(card_name: 'UC1-15', card_number: '55', weight: '1', pack_rarity_rate_id: '4')
PackCardRate.create(card_name: 'UC1-16', card_number: '56', weight: '1', pack_rarity_rate_id: '4')
PackCardRate.create(card_name: 'UC1-17', card_number: '57', weight: '1', pack_rarity_rate_id: '4')
PackCardRate.create(card_name: 'UC1-18', card_number: '58', weight: '1', pack_rarity_rate_id: '4')
PackCardRate.create(card_name: 'UC1-19', card_number: '59', weight: '1', pack_rarity_rate_id: '4')
PackCardRate.create(card_name: 'UC1-20', card_number: '60', weight: '1', pack_rarity_rate_id: '4')
PackCardRate.create(card_name: 'C1-1', card_number: '61', weight: '1', pack_rarity_rate_id: '5')
PackCardRate.create(card_name: 'C1-2', card_number: '62', weight: '1', pack_rarity_rate_id: '5')
PackCardRate.create(card_name: 'C1-3', card_number: '63', weight: '1', pack_rarity_rate_id: '5')
PackCardRate.create(card_name: 'C1-4', card_number: '64', weight: '1', pack_rarity_rate_id: '5')
PackCardRate.create(card_name: 'C1-5', card_number: '65', weight: '1', pack_rarity_rate_id: '5')
PackCardRate.create(card_name: 'C1-6', card_number: '66', weight: '1', pack_rarity_rate_id: '5')
PackCardRate.create(card_name: 'C1-7', card_number: '67', weight: '1', pack_rarity_rate_id: '5')
PackCardRate.create(card_name: 'C1-8', card_number: '68', weight: '1', pack_rarity_rate_id: '5')
PackCardRate.create(card_name: 'C1-9', card_number: '69', weight: '1', pack_rarity_rate_id: '5')
PackCardRate.create(card_name: 'C1-10', card_number: '70', weight: '1', pack_rarity_rate_id: '5')
PackCardRate.create(card_name: 'C1-11', card_number: '71', weight: '1', pack_rarity_rate_id: '5')
PackCardRate.create(card_name: 'C1-12', card_number: '72', weight: '1', pack_rarity_rate_id: '5')
PackCardRate.create(card_name: 'C1-13', card_number: '73', weight: '1', pack_rarity_rate_id: '5')
PackCardRate.create(card_name: 'C1-14', card_number: '74', weight: '1', pack_rarity_rate_id: '5')
PackCardRate.create(card_name: 'C1-15', card_number: '75', weight: '1', pack_rarity_rate_id: '5')
PackCardRate.create(card_name: 'C1-16', card_number: '76', weight: '1', pack_rarity_rate_id: '5')
PackCardRate.create(card_name: 'C1-17', card_number: '77', weight: '1', pack_rarity_rate_id: '5')
PackCardRate.create(card_name: 'C1-18', card_number: '78', weight: '1', pack_rarity_rate_id: '5')
PackCardRate.create(card_name: 'C1-19', card_number: '79', weight: '1', pack_rarity_rate_id: '5')
PackCardRate.create(card_name: 'C1-20', card_number: '80', weight: '1', pack_rarity_rate_id: '5')
PackCardRate.create(card_name: 'C1-21', card_number: '81', weight: '1', pack_rarity_rate_id: '5')
PackCardRate.create(card_name: 'C1-22', card_number: '82', weight: '1', pack_rarity_rate_id: '5')
PackCardRate.create(card_name: 'C1-23', card_number: '83', weight: '1', pack_rarity_rate_id: '5')
PackCardRate.create(card_name: 'C1-24', card_number: '84', weight: '1', pack_rarity_rate_id: '5')
PackCardRate.create(card_name: 'C1-25', card_number: '85', weight: '1', pack_rarity_rate_id: '5')

PackCardRate.create(card_name: 'SR1-1', card_number: '1', weight: '1', pack_rarity_rate_id: '6')
PackCardRate.create(card_name: 'SR1-2', card_number: '2', weight: '1', pack_rarity_rate_id: '6')
PackCardRate.create(card_name: 'SR1-3', card_number: '3', weight: '1', pack_rarity_rate_id: '6')
PackCardRate.create(card_name: 'SR1-4', card_number: '4', weight: '1', pack_rarity_rate_id: '6')
PackCardRate.create(card_name: 'SR1-5', card_number: '5', weight: '1', pack_rarity_rate_id: '6')
PackCardRate.create(card_name: 'SR1-6', card_number: '6', weight: '1', pack_rarity_rate_id: '6')
PackCardRate.create(card_name: 'SR1-7', card_number: '7', weight: '1', pack_rarity_rate_id: '6')
PackCardRate.create(card_name: 'SR1-8', card_number: '8', weight: '1', pack_rarity_rate_id: '6')
PackCardRate.create(card_name: 'SR1-9', card_number: '9', weight: '1', pack_rarity_rate_id: '6')
PackCardRate.create(card_name: 'SR1-10', card_number: '10', weight: '1', pack_rarity_rate_id: '6')
PackCardRate.create(card_name: 'VR1-1', card_number: '11', weight: '1', pack_rarity_rate_id: '7')
PackCardRate.create(card_name: 'VR1-2', card_number: '12', weight: '1', pack_rarity_rate_id: '7')
PackCardRate.create(card_name: 'VR1-3', card_number: '13', weight: '1', pack_rarity_rate_id: '7')
PackCardRate.create(card_name: 'VR1-4', card_number: '14', weight: '1', pack_rarity_rate_id: '7')
PackCardRate.create(card_name: 'VR1-5', card_number: '15', weight: '1', pack_rarity_rate_id: '7')
PackCardRate.create(card_name: 'VR1-6', card_number: '16', weight: '1', pack_rarity_rate_id: '7')
PackCardRate.create(card_name: 'VR1-7', card_number: '17', weight: '1', pack_rarity_rate_id: '7')
PackCardRate.create(card_name: 'VR1-8', card_number: '18', weight: '1', pack_rarity_rate_id: '7')
PackCardRate.create(card_name: 'VR1-9', card_number: '19', weight: '1', pack_rarity_rate_id: '7')
PackCardRate.create(card_name: 'VR1-10', card_number: '20', weight: '1', pack_rarity_rate_id: '7')
PackCardRate.create(card_name: 'R1-1', card_number: '21', weight: '1', pack_rarity_rate_id: '8')
PackCardRate.create(card_name: 'R1-2', card_number: '22', weight: '1', pack_rarity_rate_id: '8')
PackCardRate.create(card_name: 'R1-3', card_number: '23', weight: '1', pack_rarity_rate_id: '8')
PackCardRate.create(card_name: 'R1-4', card_number: '24', weight: '1', pack_rarity_rate_id: '8')
PackCardRate.create(card_name: 'R1-5', card_number: '25', weight: '1', pack_rarity_rate_id: '8')
PackCardRate.create(card_name: 'R1-6', card_number: '26', weight: '1', pack_rarity_rate_id: '8')
PackCardRate.create(card_name: 'R1-7', card_number: '27', weight: '1', pack_rarity_rate_id: '8')
PackCardRate.create(card_name: 'R1-8', card_number: '28', weight: '1', pack_rarity_rate_id: '8')
PackCardRate.create(card_name: 'R1-9', card_number: '29', weight: '1', pack_rarity_rate_id: '8')
PackCardRate.create(card_name: 'R1-10', card_number: '30', weight: '1', pack_rarity_rate_id: '8')
PackCardRate.create(card_name: 'R1-11', card_number: '31', weight: '1', pack_rarity_rate_id: '8')
PackCardRate.create(card_name: 'R1-12', card_number: '32', weight: '1', pack_rarity_rate_id: '8')
PackCardRate.create(card_name: 'R1-13', card_number: '33', weight: '1', pack_rarity_rate_id: '8')
PackCardRate.create(card_name: 'R1-14', card_number: '34', weight: '1', pack_rarity_rate_id: '8')
PackCardRate.create(card_name: 'R1-15', card_number: '35', weight: '1', pack_rarity_rate_id: '8')
PackCardRate.create(card_name: 'R1-16', card_number: '36', weight: '1', pack_rarity_rate_id: '8')
PackCardRate.create(card_name: 'R1-17', card_number: '37', weight: '1', pack_rarity_rate_id: '8')
PackCardRate.create(card_name: 'R1-18', card_number: '38', weight: '1', pack_rarity_rate_id: '8')
PackCardRate.create(card_name: 'R1-19', card_number: '39', weight: '1', pack_rarity_rate_id: '8')
PackCardRate.create(card_name: 'R1-20', card_number: '40', weight: '1', pack_rarity_rate_id: '8')
PackCardRate.create(card_name: 'UC1-1', card_number: '41', weight: '1', pack_rarity_rate_id: '9')
PackCardRate.create(card_name: 'UC1-2', card_number: '42', weight: '1', pack_rarity_rate_id: '9')
PackCardRate.create(card_name: 'UC1-3', card_number: '43', weight: '1', pack_rarity_rate_id: '9')
PackCardRate.create(card_name: 'UC1-4', card_number: '44', weight: '1', pack_rarity_rate_id: '9')
PackCardRate.create(card_name: 'UC1-5', card_number: '45', weight: '1', pack_rarity_rate_id: '9')
PackCardRate.create(card_name: 'UC1-6', card_number: '46', weight: '1', pack_rarity_rate_id: '9')
PackCardRate.create(card_name: 'UC1-7', card_number: '47', weight: '1', pack_rarity_rate_id: '9')
PackCardRate.create(card_name: 'UC1-8', card_number: '48', weight: '1', pack_rarity_rate_id: '9')
PackCardRate.create(card_name: 'UC1-9', card_number: '49', weight: '1', pack_rarity_rate_id: '9')
PackCardRate.create(card_name: 'UC1-10', card_number: '50', weight: '1', pack_rarity_rate_id: '9')
PackCardRate.create(card_name: 'UC1-11', card_number: '51', weight: '1', pack_rarity_rate_id: '9')
PackCardRate.create(card_name: 'UC1-12', card_number: '52', weight: '1', pack_rarity_rate_id: '9')
PackCardRate.create(card_name: 'UC1-13', card_number: '53', weight: '1', pack_rarity_rate_id: '9')
PackCardRate.create(card_name: 'UC1-14', card_number: '54', weight: '1', pack_rarity_rate_id: '9')
PackCardRate.create(card_name: 'UC1-15', card_number: '55', weight: '1', pack_rarity_rate_id: '9')
PackCardRate.create(card_name: 'UC1-16', card_number: '56', weight: '1', pack_rarity_rate_id: '9')
PackCardRate.create(card_name: 'UC1-17', card_number: '57', weight: '1', pack_rarity_rate_id: '9')
PackCardRate.create(card_name: 'UC1-18', card_number: '58', weight: '1', pack_rarity_rate_id: '9')
PackCardRate.create(card_name: 'UC1-19', card_number: '59', weight: '1', pack_rarity_rate_id: '9')
PackCardRate.create(card_name: 'UC1-20', card_number: '60', weight: '1', pack_rarity_rate_id: '9')
PackCardRate.create(card_name: 'C1-1', card_number: '61', weight: '1', pack_rarity_rate_id: '10')
PackCardRate.create(card_name: 'C1-2', card_number: '62', weight: '1', pack_rarity_rate_id: '10')
PackCardRate.create(card_name: 'C1-3', card_number: '63', weight: '1', pack_rarity_rate_id: '10')
PackCardRate.create(card_name: 'C1-4', card_number: '64', weight: '1', pack_rarity_rate_id: '10')
PackCardRate.create(card_name: 'C1-5', card_number: '65', weight: '1', pack_rarity_rate_id: '10')
PackCardRate.create(card_name: 'C1-6', card_number: '66', weight: '1', pack_rarity_rate_id: '10')
PackCardRate.create(card_name: 'C1-7', card_number: '67', weight: '1', pack_rarity_rate_id: '10')
PackCardRate.create(card_name: 'C1-8', card_number: '68', weight: '1', pack_rarity_rate_id: '10')
PackCardRate.create(card_name: 'C1-9', card_number: '69', weight: '1', pack_rarity_rate_id: '10')
PackCardRate.create(card_name: 'C1-10', card_number: '70', weight: '1', pack_rarity_rate_id: '10')
PackCardRate.create(card_name: 'C1-11', card_number: '71', weight: '1', pack_rarity_rate_id: '10')
PackCardRate.create(card_name: 'C1-12', card_number: '72', weight: '1', pack_rarity_rate_id: '10')
PackCardRate.create(card_name: 'C1-13', card_number: '73', weight: '1', pack_rarity_rate_id: '10')
PackCardRate.create(card_name: 'C1-14', card_number: '74', weight: '1', pack_rarity_rate_id: '10')
PackCardRate.create(card_name: 'C1-15', card_number: '75', weight: '1', pack_rarity_rate_id: '10')
PackCardRate.create(card_name: 'C1-16', card_number: '76', weight: '1', pack_rarity_rate_id: '10')
PackCardRate.create(card_name: 'C1-17', card_number: '77', weight: '1', pack_rarity_rate_id: '10')
PackCardRate.create(card_name: 'C1-18', card_number: '78', weight: '1', pack_rarity_rate_id: '10')
PackCardRate.create(card_name: 'C1-19', card_number: '79', weight: '1', pack_rarity_rate_id: '10')
PackCardRate.create(card_name: 'C1-20', card_number: '80', weight: '1', pack_rarity_rate_id: '10')
PackCardRate.create(card_name: 'C1-21', card_number: '81', weight: '1', pack_rarity_rate_id: '10')
PackCardRate.create(card_name: 'C1-22', card_number: '82', weight: '1', pack_rarity_rate_id: '10')
PackCardRate.create(card_name: 'C1-23', card_number: '83', weight: '1', pack_rarity_rate_id: '10')
PackCardRate.create(card_name: 'C1-24', card_number: '84', weight: '1', pack_rarity_rate_id: '10')
PackCardRate.create(card_name: 'C1-25', card_number: '85', weight: '1', pack_rarity_rate_id: '10')

PackCardRate.create(card_name: 'SR2-1', card_number: '86', weight: '1', pack_rarity_rate_id: '11')
PackCardRate.create(card_name: 'SR2-2', card_number: '87', weight: '1', pack_rarity_rate_id: '11')
PackCardRate.create(card_name: 'SR2-3', card_number: '88', weight: '1', pack_rarity_rate_id: '11')
PackCardRate.create(card_name: 'SR2-4', card_number: '89', weight: '1', pack_rarity_rate_id: '11')
PackCardRate.create(card_name: 'SR2-5', card_number: '90', weight: '1', pack_rarity_rate_id: '11')
PackCardRate.create(card_name: 'SR2-6', card_number: '91', weight: '1', pack_rarity_rate_id: '11')
PackCardRate.create(card_name: 'SR2-7', card_number: '92', weight: '1', pack_rarity_rate_id: '11')
PackCardRate.create(card_name: 'SR2-8', card_number: '93', weight: '1', pack_rarity_rate_id: '11')
PackCardRate.create(card_name: 'SR2-9', card_number: '94', weight: '1', pack_rarity_rate_id: '11')
PackCardRate.create(card_name: 'SR2-10', card_number: '95', weight: '1', pack_rarity_rate_id: '11')
PackCardRate.create(card_name: 'VR2-1', card_number: '96', weight: '1', pack_rarity_rate_id: '12')
PackCardRate.create(card_name: 'VR2-2', card_number: '97', weight: '1', pack_rarity_rate_id: '12')
PackCardRate.create(card_name: 'VR2-3', card_number: '98', weight: '1', pack_rarity_rate_id: '12')
PackCardRate.create(card_name: 'VR2-4', card_number: '99', weight: '1', pack_rarity_rate_id: '12')
PackCardRate.create(card_name: 'VR2-5', card_number: '100', weight: '1', pack_rarity_rate_id: '12')
PackCardRate.create(card_name: 'VR2-6', card_number: '101', weight: '1', pack_rarity_rate_id: '12')
PackCardRate.create(card_name: 'VR2-7', card_number: '102', weight: '1', pack_rarity_rate_id: '12')
PackCardRate.create(card_name: 'VR2-8', card_number: '103', weight: '1', pack_rarity_rate_id: '12')
PackCardRate.create(card_name: 'VR2-9', card_number: '104', weight: '1', pack_rarity_rate_id: '12')
PackCardRate.create(card_name: 'VR2-10', card_number: '105', weight: '1', pack_rarity_rate_id: '12')
PackCardRate.create(card_name: 'R2-1', card_number: '106', weight: '1', pack_rarity_rate_id: '13')
PackCardRate.create(card_name: 'R2-2', card_number: '107', weight: '1', pack_rarity_rate_id: '13')
PackCardRate.create(card_name: 'R2-3', card_number: '108', weight: '1', pack_rarity_rate_id: '13')
PackCardRate.create(card_name: 'R2-4', card_number: '109', weight: '1', pack_rarity_rate_id: '13')
PackCardRate.create(card_name: 'R2-5', card_number: '110', weight: '1', pack_rarity_rate_id: '13')
PackCardRate.create(card_name: 'R2-6', card_number: '111', weight: '1', pack_rarity_rate_id: '13')
PackCardRate.create(card_name: 'R2-7', card_number: '112', weight: '1', pack_rarity_rate_id: '13')
PackCardRate.create(card_name: 'R2-8', card_number: '113', weight: '1', pack_rarity_rate_id: '13')
PackCardRate.create(card_name: 'R2-9', card_number: '114', weight: '1', pack_rarity_rate_id: '13')
PackCardRate.create(card_name: 'R2-10', card_number: '115', weight: '1', pack_rarity_rate_id: '13')
PackCardRate.create(card_name: 'R2-11', card_number: '116', weight: '1', pack_rarity_rate_id: '13')
PackCardRate.create(card_name: 'R2-12', card_number: '117', weight: '1', pack_rarity_rate_id: '13')
PackCardRate.create(card_name: 'R2-13', card_number: '118', weight: '1', pack_rarity_rate_id: '13')
PackCardRate.create(card_name: 'R2-14', card_number: '119', weight: '1', pack_rarity_rate_id: '13')
PackCardRate.create(card_name: 'R2-15', card_number: '120', weight: '1', pack_rarity_rate_id: '13')
PackCardRate.create(card_name: 'R2-16', card_number: '121', weight: '1', pack_rarity_rate_id: '13')
PackCardRate.create(card_name: 'R2-17', card_number: '122', weight: '1', pack_rarity_rate_id: '13')
PackCardRate.create(card_name: 'R2-18', card_number: '123', weight: '1', pack_rarity_rate_id: '13')
PackCardRate.create(card_name: 'R2-19', card_number: '124', weight: '1', pack_rarity_rate_id: '13')
PackCardRate.create(card_name: 'R2-20', card_number: '125', weight: '1', pack_rarity_rate_id: '13')
PackCardRate.create(card_name: 'UC2-1', card_number: '126', weight: '1', pack_rarity_rate_id: '14')
PackCardRate.create(card_name: 'UC2-2', card_number: '127', weight: '1', pack_rarity_rate_id: '14')
PackCardRate.create(card_name: 'UC2-3', card_number: '128', weight: '1', pack_rarity_rate_id: '14')
PackCardRate.create(card_name: 'UC2-4', card_number: '129', weight: '1', pack_rarity_rate_id: '14')
PackCardRate.create(card_name: 'UC2-5', card_number: '130', weight: '1', pack_rarity_rate_id: '14')
PackCardRate.create(card_name: 'UC2-6', card_number: '131', weight: '1', pack_rarity_rate_id: '14')
PackCardRate.create(card_name: 'UC2-7', card_number: '132', weight: '1', pack_rarity_rate_id: '14')
PackCardRate.create(card_name: 'UC2-8', card_number: '133', weight: '1', pack_rarity_rate_id: '14')
PackCardRate.create(card_name: 'UC2-9', card_number: '134', weight: '1', pack_rarity_rate_id: '14')
PackCardRate.create(card_name: 'UC2-10', card_number: '135', weight: '1', pack_rarity_rate_id: '14')
PackCardRate.create(card_name: 'UC2-11', card_number: '136', weight: '1', pack_rarity_rate_id: '14')
PackCardRate.create(card_name: 'UC2-12', card_number: '137', weight: '1', pack_rarity_rate_id: '14')
PackCardRate.create(card_name: 'UC2-13', card_number: '138', weight: '1', pack_rarity_rate_id: '14')
PackCardRate.create(card_name: 'UC2-14', card_number: '139', weight: '1', pack_rarity_rate_id: '14')
PackCardRate.create(card_name: 'UC2-15', card_number: '140', weight: '1', pack_rarity_rate_id: '14')
PackCardRate.create(card_name: 'UC2-16', card_number: '141', weight: '1', pack_rarity_rate_id: '14')
PackCardRate.create(card_name: 'UC2-17', card_number: '142', weight: '1', pack_rarity_rate_id: '14')
PackCardRate.create(card_name: 'UC2-18', card_number: '143', weight: '1', pack_rarity_rate_id: '14')
PackCardRate.create(card_name: 'UC2-19', card_number: '144', weight: '1', pack_rarity_rate_id: '14')
PackCardRate.create(card_name: 'UC2-20', card_number: '145', weight: '1', pack_rarity_rate_id: '14')
PackCardRate.create(card_name: 'C2-1', card_number: '146', weight: '1', pack_rarity_rate_id: '15')
PackCardRate.create(card_name: 'C2-2', card_number: '147', weight: '1', pack_rarity_rate_id: '15')
PackCardRate.create(card_name: 'C2-3', card_number: '148', weight: '1', pack_rarity_rate_id: '15')
PackCardRate.create(card_name: 'C2-4', card_number: '149', weight: '1', pack_rarity_rate_id: '15')
PackCardRate.create(card_name: 'C2-5', card_number: '150', weight: '1', pack_rarity_rate_id: '15')
PackCardRate.create(card_name: 'C2-6', card_number: '151', weight: '1', pack_rarity_rate_id: '15')
PackCardRate.create(card_name: 'C2-7', card_number: '152', weight: '1', pack_rarity_rate_id: '15')
PackCardRate.create(card_name: 'C2-8', card_number: '153', weight: '1', pack_rarity_rate_id: '15')
PackCardRate.create(card_name: 'C2-9', card_number: '154', weight: '1', pack_rarity_rate_id: '15')
PackCardRate.create(card_name: 'C2-10', card_number: '155', weight: '1', pack_rarity_rate_id: '15')
PackCardRate.create(card_name: 'C2-11', card_number: '156', weight: '1', pack_rarity_rate_id: '15')
PackCardRate.create(card_name: 'C2-12', card_number: '157', weight: '1', pack_rarity_rate_id: '15')
PackCardRate.create(card_name: 'C2-13', card_number: '158', weight: '1', pack_rarity_rate_id: '15')
PackCardRate.create(card_name: 'C2-14', card_number: '159', weight: '1', pack_rarity_rate_id: '15')
PackCardRate.create(card_name: 'C2-15', card_number: '160', weight: '1', pack_rarity_rate_id: '15')
PackCardRate.create(card_name: 'C2-16', card_number: '161', weight: '1', pack_rarity_rate_id: '15')
PackCardRate.create(card_name: 'C2-17', card_number: '162', weight: '1', pack_rarity_rate_id: '15')
PackCardRate.create(card_name: 'C2-18', card_number: '163', weight: '1', pack_rarity_rate_id: '15')
PackCardRate.create(card_name: 'C2-19', card_number: '164', weight: '1', pack_rarity_rate_id: '15')
PackCardRate.create(card_name: 'C2-20', card_number: '165', weight: '1', pack_rarity_rate_id: '15')
PackCardRate.create(card_name: 'C2-21', card_number: '166', weight: '1', pack_rarity_rate_id: '15')
PackCardRate.create(card_name: 'C2-22', card_number: '167', weight: '1', pack_rarity_rate_id: '15')
PackCardRate.create(card_name: 'C2-23', card_number: '168', weight: '1', pack_rarity_rate_id: '15')
PackCardRate.create(card_name: 'C2-24', card_number: '169', weight: '1', pack_rarity_rate_id: '15')
PackCardRate.create(card_name: 'C2-25', card_number: '170', weight: '1', pack_rarity_rate_id: '15')

PackCardRate.create(card_name: 'SR2-1', card_number: '86', weight: '1', pack_rarity_rate_id: '16')
PackCardRate.create(card_name: 'SR2-2', card_number: '87', weight: '1', pack_rarity_rate_id: '16')
PackCardRate.create(card_name: 'SR2-3', card_number: '88', weight: '1', pack_rarity_rate_id: '16')
PackCardRate.create(card_name: 'SR2-4', card_number: '89', weight: '1', pack_rarity_rate_id: '16')
PackCardRate.create(card_name: 'SR2-5', card_number: '90', weight: '1', pack_rarity_rate_id: '16')
PackCardRate.create(card_name: 'SR2-6', card_number: '91', weight: '1', pack_rarity_rate_id: '16')
PackCardRate.create(card_name: 'SR2-7', card_number: '92', weight: '1', pack_rarity_rate_id: '16')
PackCardRate.create(card_name: 'SR2-8', card_number: '93', weight: '1', pack_rarity_rate_id: '16')
PackCardRate.create(card_name: 'SR2-9', card_number: '94', weight: '1', pack_rarity_rate_id: '16')
PackCardRate.create(card_name: 'SR2-10', card_number: '95', weight: '1', pack_rarity_rate_id: '16')
PackCardRate.create(card_name: 'VR2-1', card_number: '96', weight: '1', pack_rarity_rate_id: '17')
PackCardRate.create(card_name: 'VR2-2', card_number: '97', weight: '1', pack_rarity_rate_id: '17')
PackCardRate.create(card_name: 'VR2-3', card_number: '98', weight: '1', pack_rarity_rate_id: '17')
PackCardRate.create(card_name: 'VR2-4', card_number: '99', weight: '1', pack_rarity_rate_id: '17')
PackCardRate.create(card_name: 'VR2-5', card_number: '100', weight: '1', pack_rarity_rate_id: '17')
PackCardRate.create(card_name: 'VR2-6', card_number: '101', weight: '1', pack_rarity_rate_id: '17')
PackCardRate.create(card_name: 'VR2-7', card_number: '102', weight: '1', pack_rarity_rate_id: '17')
PackCardRate.create(card_name: 'VR2-8', card_number: '103', weight: '1', pack_rarity_rate_id: '17')
PackCardRate.create(card_name: 'VR2-9', card_number: '104', weight: '1', pack_rarity_rate_id: '17')
PackCardRate.create(card_name: 'VR2-10', card_number: '105', weight: '1', pack_rarity_rate_id: '17')
PackCardRate.create(card_name: 'R2-1', card_number: '106', weight: '1', pack_rarity_rate_id: '18')
PackCardRate.create(card_name: 'R2-2', card_number: '107', weight: '1', pack_rarity_rate_id: '18')
PackCardRate.create(card_name: 'R2-3', card_number: '108', weight: '1', pack_rarity_rate_id: '18')
PackCardRate.create(card_name: 'R2-4', card_number: '109', weight: '1', pack_rarity_rate_id: '18')
PackCardRate.create(card_name: 'R2-5', card_number: '110', weight: '1', pack_rarity_rate_id: '18')
PackCardRate.create(card_name: 'R2-6', card_number: '111', weight: '1', pack_rarity_rate_id: '18')
PackCardRate.create(card_name: 'R2-7', card_number: '112', weight: '1', pack_rarity_rate_id: '18')
PackCardRate.create(card_name: 'R2-8', card_number: '113', weight: '1', pack_rarity_rate_id: '18')
PackCardRate.create(card_name: 'R2-9', card_number: '114', weight: '1', pack_rarity_rate_id: '18')
PackCardRate.create(card_name: 'R2-10', card_number: '115', weight: '1', pack_rarity_rate_id: '18')
PackCardRate.create(card_name: 'R2-11', card_number: '116', weight: '1', pack_rarity_rate_id: '18')
PackCardRate.create(card_name: 'R2-12', card_number: '117', weight: '1', pack_rarity_rate_id: '18')
PackCardRate.create(card_name: 'R2-13', card_number: '118', weight: '1', pack_rarity_rate_id: '18')
PackCardRate.create(card_name: 'R2-14', card_number: '119', weight: '1', pack_rarity_rate_id: '18')
PackCardRate.create(card_name: 'R2-15', card_number: '120', weight: '1', pack_rarity_rate_id: '18')
PackCardRate.create(card_name: 'R2-16', card_number: '121', weight: '1', pack_rarity_rate_id: '18')
PackCardRate.create(card_name: 'R2-17', card_number: '122', weight: '1', pack_rarity_rate_id: '18')
PackCardRate.create(card_name: 'R2-18', card_number: '123', weight: '1', pack_rarity_rate_id: '18')
PackCardRate.create(card_name: 'R2-19', card_number: '124', weight: '1', pack_rarity_rate_id: '18')
PackCardRate.create(card_name: 'R2-20', card_number: '125', weight: '1', pack_rarity_rate_id: '18')
PackCardRate.create(card_name: 'UC2-1', card_number: '126', weight: '1', pack_rarity_rate_id: '19')
PackCardRate.create(card_name: 'UC2-2', card_number: '127', weight: '1', pack_rarity_rate_id: '19')
PackCardRate.create(card_name: 'UC2-3', card_number: '128', weight: '1', pack_rarity_rate_id: '19')
PackCardRate.create(card_name: 'UC2-4', card_number: '129', weight: '1', pack_rarity_rate_id: '19')
PackCardRate.create(card_name: 'UC2-5', card_number: '130', weight: '1', pack_rarity_rate_id: '19')
PackCardRate.create(card_name: 'UC2-6', card_number: '131', weight: '1', pack_rarity_rate_id: '19')
PackCardRate.create(card_name: 'UC2-7', card_number: '132', weight: '1', pack_rarity_rate_id: '19')
PackCardRate.create(card_name: 'UC2-8', card_number: '133', weight: '1', pack_rarity_rate_id: '19')
PackCardRate.create(card_name: 'UC2-9', card_number: '134', weight: '1', pack_rarity_rate_id: '19')
PackCardRate.create(card_name: 'UC2-10', card_number: '135', weight: '1', pack_rarity_rate_id: '19')
PackCardRate.create(card_name: 'UC2-11', card_number: '136', weight: '1', pack_rarity_rate_id: '19')
PackCardRate.create(card_name: 'UC2-12', card_number: '137', weight: '1', pack_rarity_rate_id: '19')
PackCardRate.create(card_name: 'UC2-13', card_number: '138', weight: '1', pack_rarity_rate_id: '19')
PackCardRate.create(card_name: 'UC2-14', card_number: '139', weight: '1', pack_rarity_rate_id: '19')
PackCardRate.create(card_name: 'UC2-15', card_number: '140', weight: '1', pack_rarity_rate_id: '19')
PackCardRate.create(card_name: 'UC2-16', card_number: '141', weight: '1', pack_rarity_rate_id: '19')
PackCardRate.create(card_name: 'UC2-17', card_number: '142', weight: '1', pack_rarity_rate_id: '19')
PackCardRate.create(card_name: 'UC2-18', card_number: '143', weight: '1', pack_rarity_rate_id: '19')
PackCardRate.create(card_name: 'UC2-19', card_number: '144', weight: '1', pack_rarity_rate_id: '19')
PackCardRate.create(card_name: 'UC2-20', card_number: '145', weight: '1', pack_rarity_rate_id: '19')
PackCardRate.create(card_name: 'C2-1', card_number: '146', weight: '1', pack_rarity_rate_id: '20')
PackCardRate.create(card_name: 'C2-2', card_number: '147', weight: '1', pack_rarity_rate_id: '20')
PackCardRate.create(card_name: 'C2-3', card_number: '148', weight: '1', pack_rarity_rate_id: '20')
PackCardRate.create(card_name: 'C2-4', card_number: '149', weight: '1', pack_rarity_rate_id: '20')
PackCardRate.create(card_name: 'C2-5', card_number: '150', weight: '1', pack_rarity_rate_id: '20')
PackCardRate.create(card_name: 'C2-6', card_number: '151', weight: '1', pack_rarity_rate_id: '20')
PackCardRate.create(card_name: 'C2-7', card_number: '152', weight: '1', pack_rarity_rate_id: '20')
PackCardRate.create(card_name: 'C2-8', card_number: '153', weight: '1', pack_rarity_rate_id: '20')
PackCardRate.create(card_name: 'C2-9', card_number: '154', weight: '1', pack_rarity_rate_id: '20')
PackCardRate.create(card_name: 'C2-10', card_number: '155', weight: '1', pack_rarity_rate_id: '20')
PackCardRate.create(card_name: 'C2-11', card_number: '156', weight: '1', pack_rarity_rate_id: '20')
PackCardRate.create(card_name: 'C2-12', card_number: '157', weight: '1', pack_rarity_rate_id: '20')
PackCardRate.create(card_name: 'C2-13', card_number: '158', weight: '1', pack_rarity_rate_id: '20')
PackCardRate.create(card_name: 'C2-14', card_number: '159', weight: '1', pack_rarity_rate_id: '20')
PackCardRate.create(card_name: 'C2-15', card_number: '160', weight: '1', pack_rarity_rate_id: '20')
PackCardRate.create(card_name: 'C2-16', card_number: '161', weight: '1', pack_rarity_rate_id: '20')
PackCardRate.create(card_name: 'C2-17', card_number: '162', weight: '1', pack_rarity_rate_id: '20')
PackCardRate.create(card_name: 'C2-18', card_number: '163', weight: '1', pack_rarity_rate_id: '20')
PackCardRate.create(card_name: 'C2-19', card_number: '164', weight: '1', pack_rarity_rate_id: '20')
PackCardRate.create(card_name: 'C2-20', card_number: '165', weight: '1', pack_rarity_rate_id: '20')
PackCardRate.create(card_name: 'C2-21', card_number: '166', weight: '1', pack_rarity_rate_id: '20')
PackCardRate.create(card_name: 'C2-22', card_number: '167', weight: '1', pack_rarity_rate_id: '20')
PackCardRate.create(card_name: 'C2-23', card_number: '168', weight: '1', pack_rarity_rate_id: '20')
PackCardRate.create(card_name: 'C2-24', card_number: '169', weight: '1', pack_rarity_rate_id: '20')
PackCardRate.create(card_name: 'C2-25', card_number: '170', weight: '1', pack_rarity_rate_id: '20')