User.all.each do |user|
  user.articles.create(
    title: '青単ツヴァイランサー',
    deck_url: 'https://dmps.takaratomy.co.jp/deckbuilder/deck/?c=PUC3.PUC3.PUC3.PUC3.DEC5.DEC5.DEC5.DEC5.V4C4.V4C4.V4C4.V4C4.PUC2.PUC2.PUC2.4EC2.4EC2.4EC2.4EC2.JMC3.JMC3.JMC3.JMC3.PUC4.PUC4.PUC4.PUC4.DEC2.DEC2.DEC2.DEC2.DECG.DECG.DECG.V4C3.V4C3.PUAK.PUAK.PUAK.PUAK&k=DEC2',
    content: 'ALLで環境トップです。'
  )
end

Card.create(
  name: '聖霊王アルカディアス',
  card_image: 'https://lh3.googleusercontent.com/_zQ5rueCs7pQggHPKcmOd6qiSj1aa5NH1VC-SH462ZkmQ_vMmLOrmAq_1K26ROnegn8kuOSxwCZcsOEVjf8-iga7LoO1BTSlqZ3uQh9W-Q7k=w200',
  category: '進化クリーチャー',
  race: 'エンジェル・コマンド',
  civilization: '光',
  rarity: 'SR',
  cost: '6',
  power: '11500',
  effect: '■進化－エンジェル・コマンド
  W・ブレイカー
  ■誰も光以外の呪文を唱えられない。')
Card.create(name: 'SR1-2')
Card.create(name: 'SR1-3')
Card.create(name: 'SR1-4')
Card.create(name: 'SR1-5')
Card.create(name: 'SR1-6')
Card.create(name: 'SR1-7')
Card.create(name: 'SR1-8')
Card.create(name: 'SR1-9')
Card.create(name: 'SR1-10')
Card.create(name: 'VR1-1')
Card.create(name: 'VR1-2')
Card.create(name: 'VR1-3')
Card.create(name: 'VR1-4')
Card.create(name: 'VR1-5')
Card.create(name: 'VR1-6')
Card.create(name: 'VR1-7')
Card.create(name: 'VR1-8')
Card.create(name: 'VR1-9')
Card.create(name: 'VR1-10')
Card.create(name: 'R1-1')
Card.create(name: 'R1-2')
Card.create(name: 'R1-3')
Card.create(name: 'R1-4')
Card.create(name: 'R1-5')
Card.create(name: 'R1-6')
Card.create(name: 'R1-7')
Card.create(name: 'R1-8')
Card.create(name: 'R1-9')
Card.create(name: 'R1-10')
Card.create(name: 'R1-11')
Card.create(name: 'R1-12')
Card.create(name: 'R1-13')
Card.create(name: 'R1-14')
Card.create(name: 'R1-15')
Card.create(name: 'R1-16')
Card.create(name: 'R1-17')
Card.create(name: 'R1-18')
Card.create(name: 'R1-19')
Card.create(name: 'R1-20')
Card.create(name: 'UC1-1')
Card.create(name: 'UC1-2')
Card.create(name: 'UC1-3')
Card.create(name: 'UC1-4')
Card.create(name: 'UC1-5')
Card.create(name: 'UC1-6')
Card.create(name: 'UC1-7')
Card.create(name: 'UC1-8')
Card.create(name: 'UC1-9')
Card.create(name: 'UC1-10')
Card.create(name: 'UC1-11')
Card.create(name: 'UC1-12')
Card.create(name: 'UC1-13')
Card.create(name: 'UC1-14')
Card.create(name: 'UC1-15')
Card.create(name: 'UC1-16')
Card.create(name: 'UC1-17')
Card.create(name: 'UC1-18')
Card.create(name: 'UC1-19')
Card.create(name: 'UC1-20')
Card.create(name: 'C1-1')
Card.create(name: 'C1-2')
Card.create(name: 'C1-3')
Card.create(name: 'C1-4')
Card.create(name: 'C1-5')
Card.create(name: 'C1-6')
Card.create(name: 'C1-7')
Card.create(name: 'C1-8')
Card.create(name: 'C1-9')
Card.create(name: 'C1-10')
Card.create(name: 'C1-11')
Card.create(name: 'C1-12')
Card.create(name: 'C1-13')
Card.create(name: 'C1-14')
Card.create(name: 'C1-15')
Card.create(name: 'C1-16')
Card.create(name: 'C1-17')
Card.create(name: 'C1-18')
Card.create(name: 'C1-19')
Card.create(name: 'C1-20')
Card.create(name: 'C1-21')
Card.create(name: 'C1-22')
Card.create(name: 'C1-23')
Card.create(name: 'C1-24')
Card.create(name: 'C1-25')

Card.create(name: 'SR2-1')
Card.create(name: 'SR2-2')
Card.create(name: 'SR2-3')
Card.create(name: 'SR2-4')
Card.create(name: 'SR2-5')
Card.create(name: 'SR2-6')
Card.create(name: 'SR2-7')
Card.create(name: 'SR2-8')
Card.create(name: 'SR2-9')
Card.create(name: 'SR2-10')
Card.create(name: 'VR2-1')
Card.create(name: 'VR2-2')
Card.create(name: 'VR2-3')
Card.create(name: 'VR2-4')
Card.create(name: 'VR2-5')
Card.create(name: 'VR2-6')
Card.create(name: 'VR2-7')
Card.create(name: 'VR2-8')
Card.create(name: 'VR2-9')
Card.create(name: 'VR2-10')
Card.create(name: 'R2-1')
Card.create(name: 'R2-2')
Card.create(name: 'R2-3')
Card.create(name: 'R2-4')
Card.create(name: 'R2-5')
Card.create(name: 'R2-6')
Card.create(name: 'R2-7')
Card.create(name: 'R2-8')
Card.create(name: 'R2-9')
Card.create(name: 'R2-10')
Card.create(name: 'R2-11')
Card.create(name: 'R2-12')
Card.create(name: 'R2-13')
Card.create(name: 'R2-14')
Card.create(name: 'R2-15')
Card.create(name: 'R2-16')
Card.create(name: 'R2-17')
Card.create(name: 'R2-18')
Card.create(name: 'R2-19')
Card.create(name: 'R2-20')
Card.create(name: 'UC2-1')
Card.create(name: 'UC2-2')
Card.create(name: 'UC2-3')
Card.create(name: 'UC2-4')
Card.create(name: 'UC2-5')
Card.create(name: 'UC2-6')
Card.create(name: 'UC2-7')
Card.create(name: 'UC2-8')
Card.create(name: 'UC2-9')
Card.create(name: 'UC2-10')
Card.create(name: 'UC2-11')
Card.create(name: 'UC2-12')
Card.create(name: 'UC2-13')
Card.create(name: 'UC2-14')
Card.create(name: 'UC2-15')
Card.create(name: 'UC2-16')
Card.create(name: 'UC2-17')
Card.create(name: 'UC2-18')
Card.create(name: 'UC2-19')
Card.create(name: 'UC2-20')
Card.create(name: 'C2-1')
Card.create(name: 'C2-2')
Card.create(name: 'C2-3')
Card.create(name: 'C2-4')
Card.create(name: 'C2-5')
Card.create(name: 'C2-6')
Card.create(name: 'C2-7')
Card.create(name: 'C2-8')
Card.create(name: 'C2-9')
Card.create(name: 'C2-10')
Card.create(name: 'C2-11')
Card.create(name: 'C2-12')
Card.create(name: 'C2-13')
Card.create(name: 'C2-14')
Card.create(name: 'C2-15')
Card.create(name: 'C2-16')
Card.create(name: 'C2-17')
Card.create(name: 'C2-18')
Card.create(name: 'C2-19')
Card.create(name: 'C2-20')
Card.create(name: 'C2-21')
Card.create(name: 'C2-22')
Card.create(name: 'C2-23')
Card.create(name: 'C2-24')
Card.create(name: 'C2-25')

Pack.create(pack_name: 'DMPP-01:超獣の始動(単発)', pack_num: '1')
Pack.create(pack_name: 'DMPP-01:超獣の始動(10連)', pack_num: '10')
Pack.create(pack_name: 'DMPP-02:伝説の再誕(単発)', pack_num: '1')
Pack.create(pack_name: 'DMPP-02:伝説の再誕(10連)', pack_num: '10')

PackRarityRate.create(rarity: 'SR', weight: '3', pack_id: '1')
PackRarityRate.create(rarity: 'VR', weight: '9', pack_id: '1')
PackRarityRate.create(rarity: 'R', weight: '24', pack_id: '1')
PackRarityRate.create(rarity: 'UC', weight: '60', pack_id: '1')
PackRarityRate.create(rarity: 'C', weight: '104', pack_id: '1')
PackRarityRate.create(rarity: 'SR', weight: '3', pack_id: '2')
PackRarityRate.create(rarity: 'VR', weight: '9', pack_id: '2')
PackRarityRate.create(rarity: 'R', weight: '24', pack_id: '2')
PackRarityRate.create(rarity: 'UC', weight: '60', pack_id: '2')
PackRarityRate.create(rarity: 'C', weight: '104', pack_id: '2')
PackRarityRate.create(rarity: 'SR', weight: '3', pack_id: '3')
PackRarityRate.create(rarity: 'VR', weight: '9', pack_id: '3')
PackRarityRate.create(rarity: 'R', weight: '24', pack_id: '3')
PackRarityRate.create(rarity: 'UC', weight: '60', pack_id: '3')
PackRarityRate.create(rarity: 'C', weight: '104', pack_id: '3')
PackRarityRate.create(rarity: 'SR', weight: '3', pack_id: '4')
PackRarityRate.create(rarity: 'VR', weight: '9', pack_id: '4')
PackRarityRate.create(rarity: 'R', weight: '24', pack_id: '4')
PackRarityRate.create(rarity: 'UC', weight: '60', pack_id: '4')
PackRarityRate.create(rarity: 'C', weight: '104', pack_id: '4')

PackCardRate.create(card_name: 'SR1-1', card_id: '1', weight: '1', pack_rarity_rate_id: '1')
PackCardRate.create(card_name: 'SR1-2', card_id: '2', weight: '1', pack_rarity_rate_id: '1')
PackCardRate.create(card_name: 'SR1-3', card_id: '3', weight: '1', pack_rarity_rate_id: '1')
PackCardRate.create(card_name: 'SR1-4', card_id: '4', weight: '1', pack_rarity_rate_id: '1')
PackCardRate.create(card_name: 'SR1-5', card_id: '5', weight: '1', pack_rarity_rate_id: '1')
PackCardRate.create(card_name: 'SR1-6', card_id: '6', weight: '1', pack_rarity_rate_id: '1')
PackCardRate.create(card_name: 'SR1-7', card_id: '7', weight: '1', pack_rarity_rate_id: '1')
PackCardRate.create(card_name: 'SR1-8', card_id: '8', weight: '1', pack_rarity_rate_id: '1')
PackCardRate.create(card_name: 'SR1-9', card_id: '9', weight: '1', pack_rarity_rate_id: '1')
PackCardRate.create(card_name: 'SR1-10', card_id: '10', weight: '1', pack_rarity_rate_id: '1')
PackCardRate.create(card_name: 'VR1-1', card_id: '11', weight: '1', pack_rarity_rate_id: '2')
PackCardRate.create(card_name: 'VR1-2', card_id: '12', weight: '1', pack_rarity_rate_id: '2')
PackCardRate.create(card_name: 'VR1-3', card_id: '13', weight: '1', pack_rarity_rate_id: '2')
PackCardRate.create(card_name: 'VR1-4', card_id: '14', weight: '1', pack_rarity_rate_id: '2')
PackCardRate.create(card_name: 'VR1-5', card_id: '15', weight: '1', pack_rarity_rate_id: '2')
PackCardRate.create(card_name: 'VR1-6', card_id: '16', weight: '1', pack_rarity_rate_id: '2')
PackCardRate.create(card_name: 'VR1-7', card_id: '17', weight: '1', pack_rarity_rate_id: '2')
PackCardRate.create(card_name: 'VR1-8', card_id: '18', weight: '1', pack_rarity_rate_id: '2')
PackCardRate.create(card_name: 'VR1-9', card_id: '19', weight: '1', pack_rarity_rate_id: '2')
PackCardRate.create(card_name: 'VR1-10', card_id: '20', weight: '1', pack_rarity_rate_id: '2')
PackCardRate.create(card_name: 'R1-1', card_id: '21', weight: '1', pack_rarity_rate_id: '3')
PackCardRate.create(card_name: 'R1-2', card_id: '22', weight: '1', pack_rarity_rate_id: '3')
PackCardRate.create(card_name: 'R1-3', card_id: '23', weight: '1', pack_rarity_rate_id: '3')
PackCardRate.create(card_name: 'R1-4', card_id: '24', weight: '1', pack_rarity_rate_id: '3')
PackCardRate.create(card_name: 'R1-5', card_id: '25', weight: '1', pack_rarity_rate_id: '3')
PackCardRate.create(card_name: 'R1-6', card_id: '26', weight: '1', pack_rarity_rate_id: '3')
PackCardRate.create(card_name: 'R1-7', card_id: '27', weight: '1', pack_rarity_rate_id: '3')
PackCardRate.create(card_name: 'R1-8', card_id: '28', weight: '1', pack_rarity_rate_id: '3')
PackCardRate.create(card_name: 'R1-9', card_id: '29', weight: '1', pack_rarity_rate_id: '3')
PackCardRate.create(card_name: 'R1-10', card_id: '30', weight: '1', pack_rarity_rate_id: '3')
PackCardRate.create(card_name: 'R1-11', card_id: '31', weight: '1', pack_rarity_rate_id: '3')
PackCardRate.create(card_name: 'R1-12', card_id: '32', weight: '1', pack_rarity_rate_id: '3')
PackCardRate.create(card_name: 'R1-13', card_id: '33', weight: '1', pack_rarity_rate_id: '3')
PackCardRate.create(card_name: 'R1-14', card_id: '34', weight: '1', pack_rarity_rate_id: '3')
PackCardRate.create(card_name: 'R1-15', card_id: '35', weight: '1', pack_rarity_rate_id: '3')
PackCardRate.create(card_name: 'R1-16', card_id: '36', weight: '1', pack_rarity_rate_id: '3')
PackCardRate.create(card_name: 'R1-17', card_id: '37', weight: '1', pack_rarity_rate_id: '3')
PackCardRate.create(card_name: 'R1-18', card_id: '38', weight: '1', pack_rarity_rate_id: '3')
PackCardRate.create(card_name: 'R1-19', card_id: '39', weight: '1', pack_rarity_rate_id: '3')
PackCardRate.create(card_name: 'R1-20', card_id: '40', weight: '1', pack_rarity_rate_id: '3')
PackCardRate.create(card_name: 'UC1-1', card_id: '41', weight: '1', pack_rarity_rate_id: '4')
PackCardRate.create(card_name: 'UC1-2', card_id: '42', weight: '1', pack_rarity_rate_id: '4')
PackCardRate.create(card_name: 'UC1-3', card_id: '43', weight: '1', pack_rarity_rate_id: '4')
PackCardRate.create(card_name: 'UC1-4', card_id: '44', weight: '1', pack_rarity_rate_id: '4')
PackCardRate.create(card_name: 'UC1-5', card_id: '45', weight: '1', pack_rarity_rate_id: '4')
PackCardRate.create(card_name: 'UC1-6', card_id: '46', weight: '1', pack_rarity_rate_id: '4')
PackCardRate.create(card_name: 'UC1-7', card_id: '47', weight: '1', pack_rarity_rate_id: '4')
PackCardRate.create(card_name: 'UC1-8', card_id: '48', weight: '1', pack_rarity_rate_id: '4')
PackCardRate.create(card_name: 'UC1-9', card_id: '49', weight: '1', pack_rarity_rate_id: '4')
PackCardRate.create(card_name: 'UC1-10', card_id: '50', weight: '1', pack_rarity_rate_id: '4')
PackCardRate.create(card_name: 'UC1-11', card_id: '51', weight: '1', pack_rarity_rate_id: '4')
PackCardRate.create(card_name: 'UC1-12', card_id: '52', weight: '1', pack_rarity_rate_id: '4')
PackCardRate.create(card_name: 'UC1-13', card_id: '53', weight: '1', pack_rarity_rate_id: '4')
PackCardRate.create(card_name: 'UC1-14', card_id: '54', weight: '1', pack_rarity_rate_id: '4')
PackCardRate.create(card_name: 'UC1-15', card_id: '55', weight: '1', pack_rarity_rate_id: '4')
PackCardRate.create(card_name: 'UC1-16', card_id: '56', weight: '1', pack_rarity_rate_id: '4')
PackCardRate.create(card_name: 'UC1-17', card_id: '57', weight: '1', pack_rarity_rate_id: '4')
PackCardRate.create(card_name: 'UC1-18', card_id: '58', weight: '1', pack_rarity_rate_id: '4')
PackCardRate.create(card_name: 'UC1-19', card_id: '59', weight: '1', pack_rarity_rate_id: '4')
PackCardRate.create(card_name: 'UC1-20', card_id: '60', weight: '1', pack_rarity_rate_id: '4')
PackCardRate.create(card_name: 'C1-1', card_id: '61', weight: '1', pack_rarity_rate_id: '5')
PackCardRate.create(card_name: 'C1-2', card_id: '62', weight: '1', pack_rarity_rate_id: '5')
PackCardRate.create(card_name: 'C1-3', card_id: '63', weight: '1', pack_rarity_rate_id: '5')
PackCardRate.create(card_name: 'C1-4', card_id: '64', weight: '1', pack_rarity_rate_id: '5')
PackCardRate.create(card_name: 'C1-5', card_id: '65', weight: '1', pack_rarity_rate_id: '5')
PackCardRate.create(card_name: 'C1-6', card_id: '66', weight: '1', pack_rarity_rate_id: '5')
PackCardRate.create(card_name: 'C1-7', card_id: '67', weight: '1', pack_rarity_rate_id: '5')
PackCardRate.create(card_name: 'C1-8', card_id: '68', weight: '1', pack_rarity_rate_id: '5')
PackCardRate.create(card_name: 'C1-9', card_id: '69', weight: '1', pack_rarity_rate_id: '5')
PackCardRate.create(card_name: 'C1-10', card_id: '70', weight: '1', pack_rarity_rate_id: '5')
PackCardRate.create(card_name: 'C1-11', card_id: '71', weight: '1', pack_rarity_rate_id: '5')
PackCardRate.create(card_name: 'C1-12', card_id: '72', weight: '1', pack_rarity_rate_id: '5')
PackCardRate.create(card_name: 'C1-13', card_id: '73', weight: '1', pack_rarity_rate_id: '5')
PackCardRate.create(card_name: 'C1-14', card_id: '74', weight: '1', pack_rarity_rate_id: '5')
PackCardRate.create(card_name: 'C1-15', card_id: '75', weight: '1', pack_rarity_rate_id: '5')
PackCardRate.create(card_name: 'C1-16', card_id: '76', weight: '1', pack_rarity_rate_id: '5')
PackCardRate.create(card_name: 'C1-17', card_id: '77', weight: '1', pack_rarity_rate_id: '5')
PackCardRate.create(card_name: 'C1-18', card_id: '78', weight: '1', pack_rarity_rate_id: '5')
PackCardRate.create(card_name: 'C1-19', card_id: '79', weight: '1', pack_rarity_rate_id: '5')
PackCardRate.create(card_name: 'C1-20', card_id: '80', weight: '1', pack_rarity_rate_id: '5')
PackCardRate.create(card_name: 'C1-21', card_id: '81', weight: '1', pack_rarity_rate_id: '5')
PackCardRate.create(card_name: 'C1-22', card_id: '82', weight: '1', pack_rarity_rate_id: '5')
PackCardRate.create(card_name: 'C1-23', card_id: '83', weight: '1', pack_rarity_rate_id: '5')
PackCardRate.create(card_name: 'C1-24', card_id: '84', weight: '1', pack_rarity_rate_id: '5')
PackCardRate.create(card_name: 'C1-25', card_id: '85', weight: '1', pack_rarity_rate_id: '5')

PackCardRate.create(card_name: 'SR1-1', card_id: '1', weight: '1', pack_rarity_rate_id: '6')
PackCardRate.create(card_name: 'SR1-2', card_id: '2', weight: '1', pack_rarity_rate_id: '6')
PackCardRate.create(card_name: 'SR1-3', card_id: '3', weight: '1', pack_rarity_rate_id: '6')
PackCardRate.create(card_name: 'SR1-4', card_id: '4', weight: '1', pack_rarity_rate_id: '6')
PackCardRate.create(card_name: 'SR1-5', card_id: '5', weight: '1', pack_rarity_rate_id: '6')
PackCardRate.create(card_name: 'SR1-6', card_id: '6', weight: '1', pack_rarity_rate_id: '6')
PackCardRate.create(card_name: 'SR1-7', card_id: '7', weight: '1', pack_rarity_rate_id: '6')
PackCardRate.create(card_name: 'SR1-8', card_id: '8', weight: '1', pack_rarity_rate_id: '6')
PackCardRate.create(card_name: 'SR1-9', card_id: '9', weight: '1', pack_rarity_rate_id: '6')
PackCardRate.create(card_name: 'SR1-10', card_id: '10', weight: '1', pack_rarity_rate_id: '6')
PackCardRate.create(card_name: 'VR1-1', card_id: '11', weight: '1', pack_rarity_rate_id: '7')
PackCardRate.create(card_name: 'VR1-2', card_id: '12', weight: '1', pack_rarity_rate_id: '7')
PackCardRate.create(card_name: 'VR1-3', card_id: '13', weight: '1', pack_rarity_rate_id: '7')
PackCardRate.create(card_name: 'VR1-4', card_id: '14', weight: '1', pack_rarity_rate_id: '7')
PackCardRate.create(card_name: 'VR1-5', card_id: '15', weight: '1', pack_rarity_rate_id: '7')
PackCardRate.create(card_name: 'VR1-6', card_id: '16', weight: '1', pack_rarity_rate_id: '7')
PackCardRate.create(card_name: 'VR1-7', card_id: '17', weight: '1', pack_rarity_rate_id: '7')
PackCardRate.create(card_name: 'VR1-8', card_id: '18', weight: '1', pack_rarity_rate_id: '7')
PackCardRate.create(card_name: 'VR1-9', card_id: '19', weight: '1', pack_rarity_rate_id: '7')
PackCardRate.create(card_name: 'VR1-10', card_id: '20', weight: '1', pack_rarity_rate_id: '7')
PackCardRate.create(card_name: 'R1-1', card_id: '21', weight: '1', pack_rarity_rate_id: '8')
PackCardRate.create(card_name: 'R1-2', card_id: '22', weight: '1', pack_rarity_rate_id: '8')
PackCardRate.create(card_name: 'R1-3', card_id: '23', weight: '1', pack_rarity_rate_id: '8')
PackCardRate.create(card_name: 'R1-4', card_id: '24', weight: '1', pack_rarity_rate_id: '8')
PackCardRate.create(card_name: 'R1-5', card_id: '25', weight: '1', pack_rarity_rate_id: '8')
PackCardRate.create(card_name: 'R1-6', card_id: '26', weight: '1', pack_rarity_rate_id: '8')
PackCardRate.create(card_name: 'R1-7', card_id: '27', weight: '1', pack_rarity_rate_id: '8')
PackCardRate.create(card_name: 'R1-8', card_id: '28', weight: '1', pack_rarity_rate_id: '8')
PackCardRate.create(card_name: 'R1-9', card_id: '29', weight: '1', pack_rarity_rate_id: '8')
PackCardRate.create(card_name: 'R1-10', card_id: '30', weight: '1', pack_rarity_rate_id: '8')
PackCardRate.create(card_name: 'R1-11', card_id: '31', weight: '1', pack_rarity_rate_id: '8')
PackCardRate.create(card_name: 'R1-12', card_id: '32', weight: '1', pack_rarity_rate_id: '8')
PackCardRate.create(card_name: 'R1-13', card_id: '33', weight: '1', pack_rarity_rate_id: '8')
PackCardRate.create(card_name: 'R1-14', card_id: '34', weight: '1', pack_rarity_rate_id: '8')
PackCardRate.create(card_name: 'R1-15', card_id: '35', weight: '1', pack_rarity_rate_id: '8')
PackCardRate.create(card_name: 'R1-16', card_id: '36', weight: '1', pack_rarity_rate_id: '8')
PackCardRate.create(card_name: 'R1-17', card_id: '37', weight: '1', pack_rarity_rate_id: '8')
PackCardRate.create(card_name: 'R1-18', card_id: '38', weight: '1', pack_rarity_rate_id: '8')
PackCardRate.create(card_name: 'R1-19', card_id: '39', weight: '1', pack_rarity_rate_id: '8')
PackCardRate.create(card_name: 'R1-20', card_id: '40', weight: '1', pack_rarity_rate_id: '8')
PackCardRate.create(card_name: 'UC1-1', card_id: '41', weight: '1', pack_rarity_rate_id: '9')
PackCardRate.create(card_name: 'UC1-2', card_id: '42', weight: '1', pack_rarity_rate_id: '9')
PackCardRate.create(card_name: 'UC1-3', card_id: '43', weight: '1', pack_rarity_rate_id: '9')
PackCardRate.create(card_name: 'UC1-4', card_id: '44', weight: '1', pack_rarity_rate_id: '9')
PackCardRate.create(card_name: 'UC1-5', card_id: '45', weight: '1', pack_rarity_rate_id: '9')
PackCardRate.create(card_name: 'UC1-6', card_id: '46', weight: '1', pack_rarity_rate_id: '9')
PackCardRate.create(card_name: 'UC1-7', card_id: '47', weight: '1', pack_rarity_rate_id: '9')
PackCardRate.create(card_name: 'UC1-8', card_id: '48', weight: '1', pack_rarity_rate_id: '9')
PackCardRate.create(card_name: 'UC1-9', card_id: '49', weight: '1', pack_rarity_rate_id: '9')
PackCardRate.create(card_name: 'UC1-10', card_id: '50', weight: '1', pack_rarity_rate_id: '9')
PackCardRate.create(card_name: 'UC1-11', card_id: '51', weight: '1', pack_rarity_rate_id: '9')
PackCardRate.create(card_name: 'UC1-12', card_id: '52', weight: '1', pack_rarity_rate_id: '9')
PackCardRate.create(card_name: 'UC1-13', card_id: '53', weight: '1', pack_rarity_rate_id: '9')
PackCardRate.create(card_name: 'UC1-14', card_id: '54', weight: '1', pack_rarity_rate_id: '9')
PackCardRate.create(card_name: 'UC1-15', card_id: '55', weight: '1', pack_rarity_rate_id: '9')
PackCardRate.create(card_name: 'UC1-16', card_id: '56', weight: '1', pack_rarity_rate_id: '9')
PackCardRate.create(card_name: 'UC1-17', card_id: '57', weight: '1', pack_rarity_rate_id: '9')
PackCardRate.create(card_name: 'UC1-18', card_id: '58', weight: '1', pack_rarity_rate_id: '9')
PackCardRate.create(card_name: 'UC1-19', card_id: '59', weight: '1', pack_rarity_rate_id: '9')
PackCardRate.create(card_name: 'UC1-20', card_id: '60', weight: '1', pack_rarity_rate_id: '9')
PackCardRate.create(card_name: 'C1-1', card_id: '61', weight: '1', pack_rarity_rate_id: '10')
PackCardRate.create(card_name: 'C1-2', card_id: '62', weight: '1', pack_rarity_rate_id: '10')
PackCardRate.create(card_name: 'C1-3', card_id: '63', weight: '1', pack_rarity_rate_id: '10')
PackCardRate.create(card_name: 'C1-4', card_id: '64', weight: '1', pack_rarity_rate_id: '10')
PackCardRate.create(card_name: 'C1-5', card_id: '65', weight: '1', pack_rarity_rate_id: '10')
PackCardRate.create(card_name: 'C1-6', card_id: '66', weight: '1', pack_rarity_rate_id: '10')
PackCardRate.create(card_name: 'C1-7', card_id: '67', weight: '1', pack_rarity_rate_id: '10')
PackCardRate.create(card_name: 'C1-8', card_id: '68', weight: '1', pack_rarity_rate_id: '10')
PackCardRate.create(card_name: 'C1-9', card_id: '69', weight: '1', pack_rarity_rate_id: '10')
PackCardRate.create(card_name: 'C1-10', card_id: '70', weight: '1', pack_rarity_rate_id: '10')
PackCardRate.create(card_name: 'C1-11', card_id: '71', weight: '1', pack_rarity_rate_id: '10')
PackCardRate.create(card_name: 'C1-12', card_id: '72', weight: '1', pack_rarity_rate_id: '10')
PackCardRate.create(card_name: 'C1-13', card_id: '73', weight: '1', pack_rarity_rate_id: '10')
PackCardRate.create(card_name: 'C1-14', card_id: '74', weight: '1', pack_rarity_rate_id: '10')
PackCardRate.create(card_name: 'C1-15', card_id: '75', weight: '1', pack_rarity_rate_id: '10')
PackCardRate.create(card_name: 'C1-16', card_id: '76', weight: '1', pack_rarity_rate_id: '10')
PackCardRate.create(card_name: 'C1-17', card_id: '77', weight: '1', pack_rarity_rate_id: '10')
PackCardRate.create(card_name: 'C1-18', card_id: '78', weight: '1', pack_rarity_rate_id: '10')
PackCardRate.create(card_name: 'C1-19', card_id: '79', weight: '1', pack_rarity_rate_id: '10')
PackCardRate.create(card_name: 'C1-20', card_id: '80', weight: '1', pack_rarity_rate_id: '10')
PackCardRate.create(card_name: 'C1-21', card_id: '81', weight: '1', pack_rarity_rate_id: '10')
PackCardRate.create(card_name: 'C1-22', card_id: '82', weight: '1', pack_rarity_rate_id: '10')
PackCardRate.create(card_name: 'C1-23', card_id: '83', weight: '1', pack_rarity_rate_id: '10')
PackCardRate.create(card_name: 'C1-24', card_id: '84', weight: '1', pack_rarity_rate_id: '10')
PackCardRate.create(card_name: 'C1-25', card_id: '85', weight: '1', pack_rarity_rate_id: '10')

PackCardRate.create(card_name: 'SR2-1', card_id: '86', weight: '1', pack_rarity_rate_id: '11')
PackCardRate.create(card_name: 'SR2-2', card_id: '87', weight: '1', pack_rarity_rate_id: '11')
PackCardRate.create(card_name: 'SR2-3', card_id: '88', weight: '1', pack_rarity_rate_id: '11')
PackCardRate.create(card_name: 'SR2-4', card_id: '89', weight: '1', pack_rarity_rate_id: '11')
PackCardRate.create(card_name: 'SR2-5', card_id: '90', weight: '1', pack_rarity_rate_id: '11')
PackCardRate.create(card_name: 'SR2-6', card_id: '91', weight: '1', pack_rarity_rate_id: '11')
PackCardRate.create(card_name: 'SR2-7', card_id: '92', weight: '1', pack_rarity_rate_id: '11')
PackCardRate.create(card_name: 'SR2-8', card_id: '93', weight: '1', pack_rarity_rate_id: '11')
PackCardRate.create(card_name: 'SR2-9', card_id: '94', weight: '1', pack_rarity_rate_id: '11')
PackCardRate.create(card_name: 'SR2-10', card_id: '95', weight: '1', pack_rarity_rate_id: '11')
PackCardRate.create(card_name: 'VR2-1', card_id: '96', weight: '1', pack_rarity_rate_id: '12')
PackCardRate.create(card_name: 'VR2-2', card_id: '97', weight: '1', pack_rarity_rate_id: '12')
PackCardRate.create(card_name: 'VR2-3', card_id: '98', weight: '1', pack_rarity_rate_id: '12')
PackCardRate.create(card_name: 'VR2-4', card_id: '99', weight: '1', pack_rarity_rate_id: '12')
PackCardRate.create(card_name: 'VR2-5', card_id: '100', weight: '1', pack_rarity_rate_id: '12')
PackCardRate.create(card_name: 'VR2-6', card_id: '101', weight: '1', pack_rarity_rate_id: '12')
PackCardRate.create(card_name: 'VR2-7', card_id: '102', weight: '1', pack_rarity_rate_id: '12')
PackCardRate.create(card_name: 'VR2-8', card_id: '103', weight: '1', pack_rarity_rate_id: '12')
PackCardRate.create(card_name: 'VR2-9', card_id: '104', weight: '1', pack_rarity_rate_id: '12')
PackCardRate.create(card_name: 'VR2-10', card_id: '105', weight: '1', pack_rarity_rate_id: '12')
PackCardRate.create(card_name: 'R2-1', card_id: '106', weight: '1', pack_rarity_rate_id: '13')
PackCardRate.create(card_name: 'R2-2', card_id: '107', weight: '1', pack_rarity_rate_id: '13')
PackCardRate.create(card_name: 'R2-3', card_id: '108', weight: '1', pack_rarity_rate_id: '13')
PackCardRate.create(card_name: 'R2-4', card_id: '109', weight: '1', pack_rarity_rate_id: '13')
PackCardRate.create(card_name: 'R2-5', card_id: '110', weight: '1', pack_rarity_rate_id: '13')
PackCardRate.create(card_name: 'R2-6', card_id: '111', weight: '1', pack_rarity_rate_id: '13')
PackCardRate.create(card_name: 'R2-7', card_id: '112', weight: '1', pack_rarity_rate_id: '13')
PackCardRate.create(card_name: 'R2-8', card_id: '113', weight: '1', pack_rarity_rate_id: '13')
PackCardRate.create(card_name: 'R2-9', card_id: '114', weight: '1', pack_rarity_rate_id: '13')
PackCardRate.create(card_name: 'R2-10', card_id: '115', weight: '1', pack_rarity_rate_id: '13')
PackCardRate.create(card_name: 'R2-11', card_id: '116', weight: '1', pack_rarity_rate_id: '13')
PackCardRate.create(card_name: 'R2-12', card_id: '117', weight: '1', pack_rarity_rate_id: '13')
PackCardRate.create(card_name: 'R2-13', card_id: '118', weight: '1', pack_rarity_rate_id: '13')
PackCardRate.create(card_name: 'R2-14', card_id: '119', weight: '1', pack_rarity_rate_id: '13')
PackCardRate.create(card_name: 'R2-15', card_id: '120', weight: '1', pack_rarity_rate_id: '13')
PackCardRate.create(card_name: 'R2-16', card_id: '121', weight: '1', pack_rarity_rate_id: '13')
PackCardRate.create(card_name: 'R2-17', card_id: '122', weight: '1', pack_rarity_rate_id: '13')
PackCardRate.create(card_name: 'R2-18', card_id: '123', weight: '1', pack_rarity_rate_id: '13')
PackCardRate.create(card_name: 'R2-19', card_id: '124', weight: '1', pack_rarity_rate_id: '13')
PackCardRate.create(card_name: 'R2-20', card_id: '125', weight: '1', pack_rarity_rate_id: '13')
PackCardRate.create(card_name: 'UC2-1', card_id: '126', weight: '1', pack_rarity_rate_id: '14')
PackCardRate.create(card_name: 'UC2-2', card_id: '127', weight: '1', pack_rarity_rate_id: '14')
PackCardRate.create(card_name: 'UC2-3', card_id: '128', weight: '1', pack_rarity_rate_id: '14')
PackCardRate.create(card_name: 'UC2-4', card_id: '129', weight: '1', pack_rarity_rate_id: '14')
PackCardRate.create(card_name: 'UC2-5', card_id: '130', weight: '1', pack_rarity_rate_id: '14')
PackCardRate.create(card_name: 'UC2-6', card_id: '131', weight: '1', pack_rarity_rate_id: '14')
PackCardRate.create(card_name: 'UC2-7', card_id: '132', weight: '1', pack_rarity_rate_id: '14')
PackCardRate.create(card_name: 'UC2-8', card_id: '133', weight: '1', pack_rarity_rate_id: '14')
PackCardRate.create(card_name: 'UC2-9', card_id: '134', weight: '1', pack_rarity_rate_id: '14')
PackCardRate.create(card_name: 'UC2-10', card_id: '135', weight: '1', pack_rarity_rate_id: '14')
PackCardRate.create(card_name: 'UC2-11', card_id: '136', weight: '1', pack_rarity_rate_id: '14')
PackCardRate.create(card_name: 'UC2-12', card_id: '137', weight: '1', pack_rarity_rate_id: '14')
PackCardRate.create(card_name: 'UC2-13', card_id: '138', weight: '1', pack_rarity_rate_id: '14')
PackCardRate.create(card_name: 'UC2-14', card_id: '139', weight: '1', pack_rarity_rate_id: '14')
PackCardRate.create(card_name: 'UC2-15', card_id: '140', weight: '1', pack_rarity_rate_id: '14')
PackCardRate.create(card_name: 'UC2-16', card_id: '141', weight: '1', pack_rarity_rate_id: '14')
PackCardRate.create(card_name: 'UC2-17', card_id: '142', weight: '1', pack_rarity_rate_id: '14')
PackCardRate.create(card_name: 'UC2-18', card_id: '143', weight: '1', pack_rarity_rate_id: '14')
PackCardRate.create(card_name: 'UC2-19', card_id: '144', weight: '1', pack_rarity_rate_id: '14')
PackCardRate.create(card_name: 'UC2-20', card_id: '145', weight: '1', pack_rarity_rate_id: '14')
PackCardRate.create(card_name: 'C2-1', card_id: '146', weight: '1', pack_rarity_rate_id: '15')
PackCardRate.create(card_name: 'C2-2', card_id: '147', weight: '1', pack_rarity_rate_id: '15')
PackCardRate.create(card_name: 'C2-3', card_id: '148', weight: '1', pack_rarity_rate_id: '15')
PackCardRate.create(card_name: 'C2-4', card_id: '149', weight: '1', pack_rarity_rate_id: '15')
PackCardRate.create(card_name: 'C2-5', card_id: '150', weight: '1', pack_rarity_rate_id: '15')
PackCardRate.create(card_name: 'C2-6', card_id: '151', weight: '1', pack_rarity_rate_id: '15')
PackCardRate.create(card_name: 'C2-7', card_id: '152', weight: '1', pack_rarity_rate_id: '15')
PackCardRate.create(card_name: 'C2-8', card_id: '153', weight: '1', pack_rarity_rate_id: '15')
PackCardRate.create(card_name: 'C2-9', card_id: '154', weight: '1', pack_rarity_rate_id: '15')
PackCardRate.create(card_name: 'C2-10', card_id: '155', weight: '1', pack_rarity_rate_id: '15')
PackCardRate.create(card_name: 'C2-11', card_id: '156', weight: '1', pack_rarity_rate_id: '15')
PackCardRate.create(card_name: 'C2-12', card_id: '157', weight: '1', pack_rarity_rate_id: '15')
PackCardRate.create(card_name: 'C2-13', card_id: '158', weight: '1', pack_rarity_rate_id: '15')
PackCardRate.create(card_name: 'C2-14', card_id: '159', weight: '1', pack_rarity_rate_id: '15')
PackCardRate.create(card_name: 'C2-15', card_id: '160', weight: '1', pack_rarity_rate_id: '15')
PackCardRate.create(card_name: 'C2-16', card_id: '161', weight: '1', pack_rarity_rate_id: '15')
PackCardRate.create(card_name: 'C2-17', card_id: '162', weight: '1', pack_rarity_rate_id: '15')
PackCardRate.create(card_name: 'C2-18', card_id: '163', weight: '1', pack_rarity_rate_id: '15')
PackCardRate.create(card_name: 'C2-19', card_id: '164', weight: '1', pack_rarity_rate_id: '15')
PackCardRate.create(card_name: 'C2-20', card_id: '165', weight: '1', pack_rarity_rate_id: '15')
PackCardRate.create(card_name: 'C2-21', card_id: '166', weight: '1', pack_rarity_rate_id: '15')
PackCardRate.create(card_name: 'C2-22', card_id: '167', weight: '1', pack_rarity_rate_id: '15')
PackCardRate.create(card_name: 'C2-23', card_id: '168', weight: '1', pack_rarity_rate_id: '15')
PackCardRate.create(card_name: 'C2-24', card_id: '169', weight: '1', pack_rarity_rate_id: '15')
PackCardRate.create(card_name: 'C2-25', card_id: '170', weight: '1', pack_rarity_rate_id: '15')

PackCardRate.create(card_name: 'SR2-1', card_id: '86', weight: '1', pack_rarity_rate_id: '16')
PackCardRate.create(card_name: 'SR2-2', card_id: '87', weight: '1', pack_rarity_rate_id: '16')
PackCardRate.create(card_name: 'SR2-3', card_id: '88', weight: '1', pack_rarity_rate_id: '16')
PackCardRate.create(card_name: 'SR2-4', card_id: '89', weight: '1', pack_rarity_rate_id: '16')
PackCardRate.create(card_name: 'SR2-5', card_id: '90', weight: '1', pack_rarity_rate_id: '16')
PackCardRate.create(card_name: 'SR2-6', card_id: '91', weight: '1', pack_rarity_rate_id: '16')
PackCardRate.create(card_name: 'SR2-7', card_id: '92', weight: '1', pack_rarity_rate_id: '16')
PackCardRate.create(card_name: 'SR2-8', card_id: '93', weight: '1', pack_rarity_rate_id: '16')
PackCardRate.create(card_name: 'SR2-9', card_id: '94', weight: '1', pack_rarity_rate_id: '16')
PackCardRate.create(card_name: 'SR2-10', card_id: '95', weight: '1', pack_rarity_rate_id: '16')
PackCardRate.create(card_name: 'VR2-1', card_id: '96', weight: '1', pack_rarity_rate_id: '17')
PackCardRate.create(card_name: 'VR2-2', card_id: '97', weight: '1', pack_rarity_rate_id: '17')
PackCardRate.create(card_name: 'VR2-3', card_id: '98', weight: '1', pack_rarity_rate_id: '17')
PackCardRate.create(card_name: 'VR2-4', card_id: '99', weight: '1', pack_rarity_rate_id: '17')
PackCardRate.create(card_name: 'VR2-5', card_id: '100', weight: '1', pack_rarity_rate_id: '17')
PackCardRate.create(card_name: 'VR2-6', card_id: '101', weight: '1', pack_rarity_rate_id: '17')
PackCardRate.create(card_name: 'VR2-7', card_id: '102', weight: '1', pack_rarity_rate_id: '17')
PackCardRate.create(card_name: 'VR2-8', card_id: '103', weight: '1', pack_rarity_rate_id: '17')
PackCardRate.create(card_name: 'VR2-9', card_id: '104', weight: '1', pack_rarity_rate_id: '17')
PackCardRate.create(card_name: 'VR2-10', card_id: '105', weight: '1', pack_rarity_rate_id: '17')
PackCardRate.create(card_name: 'R2-1', card_id: '106', weight: '1', pack_rarity_rate_id: '18')
PackCardRate.create(card_name: 'R2-2', card_id: '107', weight: '1', pack_rarity_rate_id: '18')
PackCardRate.create(card_name: 'R2-3', card_id: '108', weight: '1', pack_rarity_rate_id: '18')
PackCardRate.create(card_name: 'R2-4', card_id: '109', weight: '1', pack_rarity_rate_id: '18')
PackCardRate.create(card_name: 'R2-5', card_id: '110', weight: '1', pack_rarity_rate_id: '18')
PackCardRate.create(card_name: 'R2-6', card_id: '111', weight: '1', pack_rarity_rate_id: '18')
PackCardRate.create(card_name: 'R2-7', card_id: '112', weight: '1', pack_rarity_rate_id: '18')
PackCardRate.create(card_name: 'R2-8', card_id: '113', weight: '1', pack_rarity_rate_id: '18')
PackCardRate.create(card_name: 'R2-9', card_id: '114', weight: '1', pack_rarity_rate_id: '18')
PackCardRate.create(card_name: 'R2-10', card_id: '115', weight: '1', pack_rarity_rate_id: '18')
PackCardRate.create(card_name: 'R2-11', card_id: '116', weight: '1', pack_rarity_rate_id: '18')
PackCardRate.create(card_name: 'R2-12', card_id: '117', weight: '1', pack_rarity_rate_id: '18')
PackCardRate.create(card_name: 'R2-13', card_id: '118', weight: '1', pack_rarity_rate_id: '18')
PackCardRate.create(card_name: 'R2-14', card_id: '119', weight: '1', pack_rarity_rate_id: '18')
PackCardRate.create(card_name: 'R2-15', card_id: '120', weight: '1', pack_rarity_rate_id: '18')
PackCardRate.create(card_name: 'R2-16', card_id: '121', weight: '1', pack_rarity_rate_id: '18')
PackCardRate.create(card_name: 'R2-17', card_id: '122', weight: '1', pack_rarity_rate_id: '18')
PackCardRate.create(card_name: 'R2-18', card_id: '123', weight: '1', pack_rarity_rate_id: '18')
PackCardRate.create(card_name: 'R2-19', card_id: '124', weight: '1', pack_rarity_rate_id: '18')
PackCardRate.create(card_name: 'R2-20', card_id: '125', weight: '1', pack_rarity_rate_id: '18')
PackCardRate.create(card_name: 'UC2-1', card_id: '126', weight: '1', pack_rarity_rate_id: '19')
PackCardRate.create(card_name: 'UC2-2', card_id: '127', weight: '1', pack_rarity_rate_id: '19')
PackCardRate.create(card_name: 'UC2-3', card_id: '128', weight: '1', pack_rarity_rate_id: '19')
PackCardRate.create(card_name: 'UC2-4', card_id: '129', weight: '1', pack_rarity_rate_id: '19')
PackCardRate.create(card_name: 'UC2-5', card_id: '130', weight: '1', pack_rarity_rate_id: '19')
PackCardRate.create(card_name: 'UC2-6', card_id: '131', weight: '1', pack_rarity_rate_id: '19')
PackCardRate.create(card_name: 'UC2-7', card_id: '132', weight: '1', pack_rarity_rate_id: '19')
PackCardRate.create(card_name: 'UC2-8', card_id: '133', weight: '1', pack_rarity_rate_id: '19')
PackCardRate.create(card_name: 'UC2-9', card_id: '134', weight: '1', pack_rarity_rate_id: '19')
PackCardRate.create(card_name: 'UC2-10', card_id: '135', weight: '1', pack_rarity_rate_id: '19')
PackCardRate.create(card_name: 'UC2-11', card_id: '136', weight: '1', pack_rarity_rate_id: '19')
PackCardRate.create(card_name: 'UC2-12', card_id: '137', weight: '1', pack_rarity_rate_id: '19')
PackCardRate.create(card_name: 'UC2-13', card_id: '138', weight: '1', pack_rarity_rate_id: '19')
PackCardRate.create(card_name: 'UC2-14', card_id: '139', weight: '1', pack_rarity_rate_id: '19')
PackCardRate.create(card_name: 'UC2-15', card_id: '140', weight: '1', pack_rarity_rate_id: '19')
PackCardRate.create(card_name: 'UC2-16', card_id: '141', weight: '1', pack_rarity_rate_id: '19')
PackCardRate.create(card_name: 'UC2-17', card_id: '142', weight: '1', pack_rarity_rate_id: '19')
PackCardRate.create(card_name: 'UC2-18', card_id: '143', weight: '1', pack_rarity_rate_id: '19')
PackCardRate.create(card_name: 'UC2-19', card_id: '144', weight: '1', pack_rarity_rate_id: '19')
PackCardRate.create(card_name: 'UC2-20', card_id: '145', weight: '1', pack_rarity_rate_id: '19')
PackCardRate.create(card_name: 'C2-1', card_id: '146', weight: '1', pack_rarity_rate_id: '20')
PackCardRate.create(card_name: 'C2-2', card_id: '147', weight: '1', pack_rarity_rate_id: '20')
PackCardRate.create(card_name: 'C2-3', card_id: '148', weight: '1', pack_rarity_rate_id: '20')
PackCardRate.create(card_name: 'C2-4', card_id: '149', weight: '1', pack_rarity_rate_id: '20')
PackCardRate.create(card_name: 'C2-5', card_id: '150', weight: '1', pack_rarity_rate_id: '20')
PackCardRate.create(card_name: 'C2-6', card_id: '151', weight: '1', pack_rarity_rate_id: '20')
PackCardRate.create(card_name: 'C2-7', card_id: '152', weight: '1', pack_rarity_rate_id: '20')
PackCardRate.create(card_name: 'C2-8', card_id: '153', weight: '1', pack_rarity_rate_id: '20')
PackCardRate.create(card_name: 'C2-9', card_id: '154', weight: '1', pack_rarity_rate_id: '20')
PackCardRate.create(card_name: 'C2-10', card_id: '155', weight: '1', pack_rarity_rate_id: '20')
PackCardRate.create(card_name: 'C2-11', card_id: '156', weight: '1', pack_rarity_rate_id: '20')
PackCardRate.create(card_name: 'C2-12', card_id: '157', weight: '1', pack_rarity_rate_id: '20')
PackCardRate.create(card_name: 'C2-13', card_id: '158', weight: '1', pack_rarity_rate_id: '20')
PackCardRate.create(card_name: 'C2-14', card_id: '159', weight: '1', pack_rarity_rate_id: '20')
PackCardRate.create(card_name: 'C2-15', card_id: '160', weight: '1', pack_rarity_rate_id: '20')
PackCardRate.create(card_name: 'C2-16', card_id: '161', weight: '1', pack_rarity_rate_id: '20')
PackCardRate.create(card_name: 'C2-17', card_id: '162', weight: '1', pack_rarity_rate_id: '20')
PackCardRate.create(card_name: 'C2-18', card_id: '163', weight: '1', pack_rarity_rate_id: '20')
PackCardRate.create(card_name: 'C2-19', card_id: '164', weight: '1', pack_rarity_rate_id: '20')
PackCardRate.create(card_name: 'C2-20', card_id: '165', weight: '1', pack_rarity_rate_id: '20')
PackCardRate.create(card_name: 'C2-21', card_id: '166', weight: '1', pack_rarity_rate_id: '20')
PackCardRate.create(card_name: 'C2-22', card_id: '167', weight: '1', pack_rarity_rate_id: '20')
PackCardRate.create(card_name: 'C2-23', card_id: '168', weight: '1', pack_rarity_rate_id: '20')
PackCardRate.create(card_name: 'C2-24', card_id: '169', weight: '1', pack_rarity_rate_id: '20')
PackCardRate.create(card_name: 'C2-25', card_id: '170', weight: '1', pack_rarity_rate_id: '20')